SKILLS_DB = [
    "python",
    "java",
    "javascript",
    "react",
    "node.js",
    "fastapi",
    "flask",
    "sql",
    "mongodb",
    "docker",
    "aws",
    "git",
    "machine learning",
    "data analysis",
    "tailwind css",
    "html",
    "css",
    "rest api",
]